kind: Namespace
apiVersion: v1
metadata:
  name: dev
  labels:
    name: dev
---
kind: Namespace
apiVersion: v1
metadata:
  name: stage
  labels:
    name: stage
---
kind: Namespace
apiVersion: v1
metadata:
  name: prod
  labels:
    name: prod
